module.exports = {
    name: 'help',
    description: 'This is a help command',
    execute(message, MessageEmbed) {
        if (message.author.id === '700166055326384179') {
            const embed = new MessageEmbed()
            .setColor('#02C2FF')
            .setAuthor('UniversNetwork', 'https://cdn.discordapp.com/app-icons/792994169659981846/63db7674caa58a0694d989693bc4b60a.png?size=64', 'https://minecraft-mp.com/server-s272254')
            .setTitle('**Prefix:** `.`')
            .addField('\u200B', '\u200B', true)
            .addField('Developer List Of Commands', '\u200B', true)
            .addField('\u200B', '\u200B', true)
            .addField('`.reload` `.load`', 'Untuk me-reload semua command')
            .setFooter('Made By ARVIN3108 ID', 'https://cdn.discordapp.com/avatars/700166055326384179/3ec8287199dc402fe6a587902e300749.png?size=64')
            message.author.send(embed)
        }
        const embed = new MessageEmbed()
            .setColor('#02C2FF')
            .setAuthor('UniversNetwork', 'https://cdn.discordapp.com/app-icons/792994169659981846/63db7674caa58a0694d989693bc4b60a.png?size=64', 'https://minecraft-mp.com/server-s272254')
            .setTitle('**Prefix:** `.`')
            .setDescription(':clipboard: **Diminta Oleh ' + message.author.username + '**\n\u200B\n\u200B')
            .addField('\u200B', '\u200B', true)
            .addField('Member List Of Commands', '\u200B', true)
            .addField('\u200B', '\u200B', true)
            .addField('`.help` `.?`', 'Untuk memunculkan menu ini')
            .addField('`.ip`', 'Untuk melihat ip dari server ini')
            .addField('`.play` `.p`', 'Untuk memutar lagu *(sama seperti bot musik pada umumnya)*')
            .addField('`.loop` `.repeat`', 'Untuk mengaktifkan atau menonaktifkan mode repeat lagu *(sama seperti bot musik pada umumnya)*')
            .addField('`.shuffle` `.random` `.rm`', 'Untuk mengaktifkan atau menonaktifkan mode acak lagu *(sama seperti bot musik pada umumnya)*')
            .addField('`.autoplay` `.ap`', 'Untuk mengaktifkan atau menonaktifkan mode putar lagu otomatis')
            .addField('`.skip` `.s`', 'Untuk melewati lagu yang sedang diputar *(sama seperti bot musik pada umumnya)*')
            .addField('`.queue` `.q`', 'Untuk melihat daftar lagu yang sedang diputar *(sama seperti bot musik pada umumnya)*')
            .addField('`.join` `.connect` `.summon`', 'Untuk membuat bot masuk ke voice channel *(sama seperti bot musik pada umumnya)*')
            .addField('`.leave` `.disconnect` `.dc` `.stop`', 'Untuk menghentikan dan men-disconnect bot setelah memutar lagu')
            .addField('`.vote`', 'Untuk mengunjungi link vote server ini')
            .addField('`.info`', 'Untuk melihat informasi dari server atau bot\n\u200B\n\u200B')
            .addField('\u200B', '\u200B',true)
            .addField('Admin List Of Commands', '\u200B',true)
            .addField('\u200B', '\u200B', true)
            .addField('`.kick`', 'Untuk meng-kick member')
            .addField('`.ban`', 'Untuk meng-ban member')
            .addField('`.mute`', 'Untuk meng-mute member dengan waktu atau permanen')
            .addField('`.unmute`', 'Untuk meng-unmute member')
            .addField('`.playskip` `.ps`', 'Untuk memutar dan melewati lagu secara bersamaan')
            .addField('`.volume` `.vol`', 'Untuk merubah volume suara bot saat memutar lagu')
            .addField('`.say`', 'Untuk mengirim pesan sebagai bot')
            .addField('`.clear`', 'Untuk menghapus pesan dengan cepat')
            .addField('`.verification` `.verify`', 'Untuk meng-set channel verifikasi (mirip dengan carl bot)')
            .addField('Check The Wiki For English Version', 'https://github.com/ARVIN3108/UniversNetwork/blob/main/README.md')
            .setFooter('Made By ARVIN3108 ID', 'https://cdn.discordapp.com/avatars/700166055326384179/3ec8287199dc402fe6a587902e300749.png?size=64')
        message.delete().then(message.channel.send(embed))
    }
}